#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

string_="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

# This command replace what is in  line 24 (24i) of /etc/nginx/sites-available/default
# with the content of strings
sudo sed -i  "24i\ $string_" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
