#!/usr/bin/env bash
# This bash script configures Nginx server so that /xyzfoo return 404 error and the string "Ceci n'est pas une page"

sudo apt update
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/error_404.html
# or echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.hyml

error="\terror_page 404 /error_404.html;"

# This command replace what is in  line 24 (24i) of /etc/nginx/sites-available/default
# with the content of string
sudo sed -i "26i\ $error" /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
