#!/usr/bin/env bash
# This bash script will nstall and configure HAproxy on a server

sudo apt-get -y update

# sudo apt-get -y install --no-install-recommends software-properties-common
# sudo add-apt-repository ppa:vbernat/haproxy-2.4
# sudo apt-get -y install haproxy=2.4.\*
sudo apt-get -y install haproxy

haproxy_="

frontend www
	bind *:80
	mode http
	default_backend web_nginx

backend web_nginx
	balance roundrobin
	mode http
	server 144788-web-01 54.237.110.44:80 check
	server 144788-web-02 107.23.108.80:80 check
"
echo  "$haproxy_" >>  /etc/haproxy/haproxy.cfg

# Enable haproxy
sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy

# Testing for error
# sudo haproxy -f /etc/haproxy/haproxy.cfg -c

# Restarting haproxy
sudo service haproxy restart

