#!/usr/bin/env bash
# This bash script configures a machine running nginx to listen on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
