#!/usr/bin/env bash
# This bash script gives you information about the school file.

value=0
for var in *
do
	if [ "$var" = school ]
	then
		value=1
		echo "school file exists"
		if [ -s "$var" ]
		then 
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		if [ -f "$var" ]
		then
			echo "school is a regular file"
		fi
	fi
done
if [ "$value" = 0 ]
then
	echo "school file does not exist"
fi
