#!/usr/bin/env bash
# This bash script run nginx(service) as nginx(user)
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 774 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
