#!/usr/bin/env bash
# This bash script uses ssh to connect to your server using the
# private key ~/.ssh/school with the user ubuntu.
cat ~/.ssh/school.pub | ssh ubuntu@54.175.223.104 "mkdir -p ~/.ssh && chmod 700 ~/.ssh && cat >> ~/.ssh/authorized_keys"
